### ISSUE TITLE
Add Owners - Candy (owner 4) and extra owner Bob

### ISSUE THREAD

**Issue by candycoleman** [JenniferLarsen/PetGateway#10]
ConfigureOwners - Model add

new Owner
                {
                    OwnerId = 4,
                    FirstName = "Candy",
                    LastName = "Coleman",
                    Address = "343 Cool St",
                    City = "Iowa City",
                    State = "IA",
                    PostalCode = "50335",
                    PhoneNumber = "5152342223",
                    Email = "candykaycoleman@gmail.com"
                },
new Owner
                {
                    OwnerId = 5,
                    FirstName = "Bob",
                    LastName = "Appleton",
                    Address = "23 Main St",
                    City = "Des Moines",
                    State = "IA",
                    PostalCode = "50365",
                    PhoneNumber = "5152344551",
                    Email = "appletonbob@gmail.com"
                },

**Comment by amy-miles** [comment]
You can add this info through pulling the project and adding to our ConfigurePets.cs class, if you wish.
