### ISSUE TITLE
Add Pet - Otto Candys dog w/photo

### ISSUE THREAD

**Issue by candycoleman** [JenniferLarsen/PetGateway#11]
ConfigurePet

new Pet
                {
                    PetId = 4,
                    PetName = "Otto",
                    PetType = "canine",
                    PetColor = "black and white",
                    PetBreed = "Pom",
                    PetAge = 7,
                    PetGender = "male",
                    PetWeight = 10,
                    Spayed_Neutered = true,
                    OwnerId = 4
                },

 Pet photo 

![20231117_120715](https://github.com/JenniferLarsen/PetGateway/assets/142948815/46ebe62d-b0ab-4229-9c24-2648e94750a3)

**Comment by amy-miles** [comment]
Out of scope. We will not be adding pet images for individual pets.
